export const APPOINTMENT_CREATE_REQUEST = 'APPOINTMENT_CREATE_REQUEST'
export const APPOINTMENT_CREATE_SUCCESS = 'APPOINTMENT_CREATE_SUCCESS'
export const APPOINTMENT_CREATE_FAIL = 'APPOINTMENT_CREATE_FAIL'
export const APPOINTMENT_CREATE_RESET = 'APPOINTMENT_CREATE_RESET'





export const CONSULTANTS_LIST_SUCCESS = 'CONSULTANTS_LIST_SUCCESS'
export const CONSULTANTS_LIST_FAIL = ' CONSULTANTS_LIST_FAIL '
export const CONSULTANTS_LIST_REQUEST = 'CONSULTANTS_LIST_REQUEST'



export const CONSULTANTS_DETAILS_REQUEST = 'CONSULTANTS_DETAILS_REQUEST'
export const CONSULTANTS_DETAILS_SUCCESS = 'CONSULTANTS_DETAILS_SUCCESS'
export const CONSULTANTS_DETAILS_FAIL = 'CONSULTANTS_DETAILS_FAIL'

export const CONSULTANTS_UPDATE_SUCCESS = 'CONSULTANTS_UPDATE_SUCCESS'
export const CONSULTANTS_UPDATE_FAIL = ' CONSULTANTS_UPDATE_FAIL '
export const CONSULTANTS_UPDATE_REQUEST = 'CONSULTANTS_UPDATE_REQUEST'
export const CONSULTANTS_UPDATE_RESET = 'CONSULTANTS_UPDATE_RESET'

export const CONSULTANTS_LINK_SUCCESS = 'CONSULTANTS_LINK_SUCCESS'
export const CONSULTANTS_LINK_FAIL = ' CONSULTANTS_LINK_FAIL '
export const CONSULTANTS_LINK_REQUEST = 'CONSULTANTS_LINK_REQUEST'
export const CONSULTANTS_LINK_RESET = 'CONSULTANTS_LINK_RESET'

export const CONSULTANTS_DELETE_SUCCESS = 'CONSULTANTS_DELETE_SUCCESS'
export const CONSULTANTS_DELETE_FAIL = ' CONSULTANTS_DELETE_FAIL '
export const CONSULTANTS_DELETE_REQUEST = 'CONSULTANTS_DELETE_REQUEST'
export const CONSULTANTS_DELETE_RESET = 'CONSULTANTS_DELETE_RESET'

export const CONSULTANTS_PRESCRIPTION_SUCCESS = 'CONSULTANTS_PRESCRIPTION_SUCCESS'
export const CONSULTANTS_PRESCRIPTION_FAIL = 'CONSULTANTS_DELETE_FAIL'
export const CONSULTANTS_PRESCRIPTION_REQUEST = 'CONSULTANTS_PRESCRIPTION_REQUEST'
export const CONSULTANTS_PRESCRIPTION_RESET = 'CONSULTANTS_PRESCRIPTION_RESET'