export const DASHBOARD_APPOINTMNET_REQUEST = 'DASHBOARD_APPOINTMNET_REQUEST'
export const DASHBOARD_APPOINTMNET_SUCCESS = 'DASHBOARD_APPOINTMNET_SUCCESS'
export const DASHBOARD_APPOINTMNET_FAIL = 'DASHBOARD_APPOINTMNET_FAIL'
export const DASHBOARD_APPOINTMNET_RESET = 'DASHBOARD_APPOINTMNET_RESET'


export const DASHBOARD_GETAPPOINTMNET_REQUEST = 'DASHBOARD_GETAPPOINTMNET_REQUEST'
export const DASHBOARD_GETAPPOINTMNET_SUCCESS = 'DASHBOARD_GETAPPOINTMNET_SUCCESS'
export const DASHBOARD_GETAPPOINTMNET_FAIL = 'DASHBOARD_GETAPPOINTMNET_FAIL'
export const DASHBOARD_GETAPPOINTMNET_RESET = 'DASHBOARD_GETAPPOINTMNET_RESET'