export const INQUIRY_ADD_REQUEST = 'INQUIRY_ADD_REQUEST'
export const INQUIRY_ADD_SUCCESS = 'INQUIRY_ADD_SUCCESS'
export const INQUIRY_ADD_FAIL = 'INQUIRY_ADD_FAIL'
export const INQUIRY_ADD_RESET = 'INQUIRY_ADD_RESET'