//medicine constants
export const MEDICINE_REQUEST = 'MEDICINE_REQUEST'
export const MEDICINE_SUCCESS = 'MEDICINE_SUCCESS'
export const MEDICINE_FAIL = 'MEDICINE_FAIL'
export const MEDICINE_RESET = 'MEDICINE_RESET'

//add prescription constants
export const PRESCRIPTION_REQUEST = 'PRESCRIPTION_REQUEST'
export const PRESCRIPTION_SUCCESS = 'PRESCRIPTION_SUCCESS'
export const PRESCRIPTION_FAIL = 'PRESCRIPTION_FAIL'
export const PRESCRIPTION_RESET = 'PRESCRIPTION_RESET'

//add dietchart constants
export const DIETCHART_REQUEST = 'DIETCHART_REQUEST'
export const DIETCHART_SUCCESS = 'DIETCHART_SUCCESS'
export const DIETCHART_FAIL = 'DIETCHART_FAIL'
export const DIETCHART_RESET = 'DIETCHART_RESET'

//get latest prescription constants
export const GET_PRESCRIPTION_REQUEST = 'GET_PRESCRIPTION_REQUEST'
export const GET_PRESCRIPTION_SUCCESS = 'GET_PRESCRIPTION_SUCCESS'
export const GET_PRESCRIPTION_FAIL = 'GET_PRESCRIPTION_FAIL'
export const GET_PRESCRIPTION_RESET = 'GET_PRESCRIPTION_RESET'

//get DietChart
export const GET_DIETCHART_REQUEST = 'GET_DIETCHART_REQUEST'
export const GET_DIETCHART_SUCCESS = 'GET_DIETCHART_SUCCESS'
export const GET_DIETCHART_FAIL = 'GET_DIETCHART_FAIL'
export const GET_DIETCHART_RESET = 'GET_DIETCHART_RESET'

//get  prescription constants
export const DATA_PRESCRIPTION_REQUEST = 'DATA_PRESCRIPTION_REQUEST'
export const DATA_PRESCRIPTION_SUCCESS = 'DATA_PRESCRIPTION_SUCCESS'
export const DATA_PRESCRIPTION_FAIL = 'DATA_PRESCRIPTION_FAIL'
export const DATA_PRESCRIPTION_RESET = 'DATA_PRESCRIPTION_RESET'


//get  prescription and patient constants
export const PATIENT_PRESCRIPTION_REQUEST = 'PATIENT_PRESCRIPTION_REQUEST'
export const PATIENT_PRESCRIPTION_SUCCESS = 'PATIENT_PRESCRIPTION_SUCCESS'
export const PATIENT_PRESCRIPTION_FAIL = 'PATIENT_PRESCRIPTION_FAIL'
export const PATIENT_PRESCRIPTION_RESET = 'PATIENT_PRESCRIPTION_RESET'