export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const DOCTORS_LIST_SUCCESS = 'DOCTORS_LIST_SUCCESS'
export const DOCTORS_LIST_FAIL = 'DOCTORS_LIST_FAIL'
export const DOCTORS_LIST_REQUEST = 'DOCTORS_LIST_REQUEST'

export const DOCTORS_CREATE_SUCCESS = 'DOCTORS_CREATE_SUCCESS'
export const DOCTORS_CREATE_FAIL = 'DOCTORS_CREATE_FAIL'
export const DOCTORS_CREATE_REQUEST = 'DOCTORS_CREATE_REQUEST'
export const DOCTORS_CREATE_RESET = 'DOCTORS_CREATE_RESET'


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const DOCTORS_UPDATE_SUCCESS = 'DOCTORS_UPDATE_SUCCESS'
export const DOCTORS_UPDATE_FAIL = 'DOCTORS_UPDATE_FAIL'
export const DOCTORS_UPDATE_REQUEST = 'DOCTORS_UPDATE_REQUEST'
export const DOCTORS_UPDATE_RESET = 'DOCTORS_UPDATE_RESET'

//update appointment date constants
export const DOCTORS_APPOINTMENT_SUCCESS = 'DOCTORS_APPOINTMENT_SUCCESS'
export const DOCTORS_APPOINTMENT_FAIL = 'DOCTORS_APPOINTMENT_FAIL'
export const DOCTORS_APPOINTMENT_REQUEST = 'DOCTORS_APPOINTMENT_REQUEST'
export const DOCTORS_APPOINTMENT_RESET = 'DOCTORS_APPOINTMENT_RESET'

//delete appointment date constants
export const DOCTORS_DELETE_SUCCESS = 'DOCTORS_DELETE_SUCCESS'
export const DOCTORS_DELETE_FAIL = 'DOCTORS_DELETE_FAIL'
export const DOCTORS_DELETE_REQUEST = 'DOCTORS_DELETE_REQUEST'
export const DOCTORS_DELETE_RESET = 'DOCTORS_DELETE_RESET'

//create doctor data constants
export const DOCTORS_DATA_SUCCESS = 'DOCTORS_DATA_SUCCESS'
export const DOCTORS_DATA_FAIL = 'DOCTORS_DATA_FAIL'
export const DOCTORS_DATA_REQUEST = 'DOCTORS_DATA_REQUEST'
export const DOCTORS_DATA_RESET = 'DOCTORS_DATA_RESET'