export const THERAPY_ADD_REQUEST = 'THERAPY_ADD_REQUEST'
export const THERAPY_ADD_SUCCESS = 'THERAPY_ADD_SUCCESS'
export const THERAPY_ADD_FAIL = 'THERAPY_ADD_FAIL'
export const THERAPY_ADD_RESET = 'THERAPY_ADD_RESET'