export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_INFO_DETAILS_REQUEST = 'USER_INFO_DETAILS_REQUEST'
export const USER_INFO_DETAILS_SUCCESS = 'USER_INFO_DETAILS_SUCCESS'
export const USER_INFO_DETAILS_FAIL = 'USER_INFO_DETAILS_FAIL'
export const USER_INFO_DETAILS_RESET = 'USER_INFO_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_DETAILS_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST'
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL'
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET'

export const USER_LATEST_REQUEST = 'USER_LATEST_REQUEST'
export const USER_LATEST_SUCCESS = 'USER_LATEST_SUCCESS'
export const USER_LATEST_FAIL = 'USER_LATEST_FAIL'
export const USER_LATEST_RESET = 'USER_LATEST_RESET'

export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST'
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS'
export const USER_STATUS_FAIL = 'USER_STATUS_FAIL'
export const USER_STATUS_RESET = 'USER_STATUS_RESET'